version: '3'
services:
  # web:
  #   build: ./coco
  #   ports:
  #     - "27358:27358"
  #   container_name: webtest
  #   depends_on:
  #     - redis
  #     - mongodb
  #   restart: always
  #   volumes:
  #     - ./configFileForDocker/go_webLogs:/go/logs
  #   tty: 'true'
  #   networks:
  #     mynet1:
  #       ipv4_address: 172.19.0.4

#redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-nas
    volumes:
     - /etc/localtime:/etc/localtime # make time sync
     - ./config/redis/redis.conf:/usr/local/etc/config/redis.conf
     - ./config/redis/data:/data
    restart: unless-stopped
    command: redis-server /usr/local/etc/config/redis.conf
    privileged: true
    # make netowrk connect
    networks :
      nas:
        ipv4_address: 172.66.0.2

# mongodb service
  mongodb:
    image: yowoo/my-mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo-nas
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/mongo:/data/db
    restart: unless-stopped
    command: mongod --auth --bind_ip_all --port 27017
    networks:
      nas:
        ipv4_address: 172.66.0.3

#create a new bridge named nas
networks:
  nas:
    ipam:
      config:
        - subnet: 172.66.0.0/16
